POST http://localHost:3001/register HTTP/1.1
Content-Type:application/json

{
    "username": "asdasd",
    "password": "123"
}

###

POST http://localHost:3001/register/twofactor HTTP/1.1
Content-Type:application/json

{
    "username": "asdasd",
    "hasTwoFactor": false,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZGFzZCIsInBhc3N3b3JkIjoiJDJiJDEwJEkwVlloNEwuaVlaRmNVM1JDUi52Yy45Mk43WEtuaWE0WkY0Wm45NlJVYkF2ZkdVYWhuSk9HIiwiaGFzVHdvRmFjdG9yIjpmYWxzZSwiaWF0IjoxNjM5MzMwNDM5LCJleHAiOjE2MzkzNjY0Mzl9.JaMdM7u8P0JTqx1S7ndkslXnk2hf-VY2_WqSb-7vFiU"
  }
###

POST http://localHost:3001/login HTTP/1.1
Content-Type:application/json

{
    "username": "asdasd",
    "password": "123"
}

